[package]
name = "polymap"
version = "0.1.0"
authors = ["ole_thoeb <eloemil@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
